### ISSUE TITLE
Support CommonJS exports

### ISSUE THREAD

**Issue by lxiange** [worker-tools/parsed-html-rewriter#1]
Hi, I like your project so much. 
Since currently, I'm working on a project to support Cloudflare Workers and Nodejs at the same time.
So the your `HTMLRewriter` is an excellent library as the drop-in replacement of the Cloudflare's `HTMLRewriter` API.

However, currently it doesn't support CommonJS exports. So it's a bit hard to use it in NodeJS (I know NodeJS supports ESModule now).
Supporting CJS way has following cons:
1. Easy to use in NodeJS. No need to change the existing code. We don't have to enable the `--experimental-modules`, and don't need to change the existing code either.
2. `require` is dynamic, which means the same code could be used in Cloudflare works directly, with a flag protected.

Thank you again for your project!

**Comment by qwtel** [comment]
Nice to see this have some use already :)

I've had some boilerplate for CommonJS exports, just didn't include it yet. `require` should work now out of the box.

One thing to keep in mind is that the CommonJS version is transpiled down to version ES2015, while the `import` version is at at ES2020

**Comment by lxiange** [comment]
Thank you for the timely reply & fix!
Yeah, I agree that `import` is more elegant way, in most cases. 
It's only my niche needs to be compatible with Cloudflare workers & NodeJS :-)
Thank you again and take care!
