### ISSUE TITLE
Can't be imported in Deno

### ISSUE THREAD

**Issue by lxiange** [worker-tools/parsed-html-rewriter#2]
Hi, 
When I import it in the Deno, it seems some dependencies don't work with ES module.
I understand that most libraries don't work with Deno right now, but it would be better to support Deno.

Thank you!

--

`import 'https://unpkg.com/@worker-tools/parsed-html-rewriter?module';`

```
...
Download https://unpkg.com/htmlparser2@^6.0.0?module
Download https://unpkg.com/linkedom@0.5.6/commonjs/canvas.cjs?module
Download https://unpkg.com/css-select@^3.1.2?module
Download https://unpkg.com/htmlparser2@6.0.1?module
Download https://unpkg.com/css-select@3.1.2?module
error: Import 'https://unpkg.com/css-select@3.1.2?module' failed: 404 Not Found
    at https://unpkg.com/linkedom@0.5.6/esm/shared/matches.js?module:1:0
```

**Comment by qwtel** [comment]
~~This is not something I can fix, as it's internal to one of the dependencies.~~

~~Use skypack instead: `https://cdn.skypack.dev/@worker-tools/parsed-html-rewriter`~~

~~There appears to be something wrong with it as well. In that case you'll have to use, esbuild, rollup, or webpack to bundle your code before running it in Deno...~~

See [comment below](https://github.com/worker-tools/parsed-html-rewriter/issues/2#issuecomment-912896007) for a way to import in Deno directly.

**Comment by lxiange** [comment]
Thank you for the reply.
Yeah, I know that's because of some indirect dependencies. 

But if one day we want to put this HTMLRewriter on this page: https://worker-tools.github.io/#tools
Maybe we have better to support it. So that:
> Most have no dependencies beyond what is provided by a Worker Environment. For those that have dependencies, only such that provide ES module exports are used.

Thank you so much, I learned a lot from the worker-tools.

**Comment by qwtel** [comment]
Yep fully agree.

Unfortunately I'm not sure this module will ever live up to that standard. Unlike the other tools, this one has some pretty complex dependencies and maintaining de-node-ified forks of them seems overkill. I might look into it at some point anyway.

I hope that lol-html will provide a WASM interface at some point (I think there's an open issue) which should be self-contained and make this module obsolete.


***

Anyway, nice to see you've poked around the tools  a bit 👍

**Comment by qwtel** [comment]
FYI: It's now possible to use this module directly in deno by providing the following import map:

```json
{
  "imports": {
    "linkedom": "https://esm.sh/linkedom?alias=perf_hooks:universal-perf-hooks",
    "whatwg-stream-to-async-iter": "https://esm.sh/whatwg-stream-to-async-iter",
    "tslib": "https://esm.sh/tslib"
  }
}
```

Exampel usage:

```js
#!/usr/bin/env -S deno run --import-map=./import-map.json --allow-net --no-check=remote
import { ParsedHTMLRewriter } from 'https://unpkg.com/@worker-tools/parsed-html-rewriter/index.js';
```

Mind the `--no-check` option to prevent typescript errors relating to missing DOM types.
